"""empty message

Revision ID: 1afe3a3c0aec
Revises: 2fc60f57a788
Create Date: 2024-09-27 15:06:39.434846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1afe3a3c0aec'
down_revision = '2fc60f57a788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sys_agent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('show_citation', sa.Boolean(), nullable=False),
    sa.Column('empty_response', sa.Text(), nullable=True),
    sa.Column('advanced_config', mysql.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_agent'))
    )
    with op.batch_alter_table('t_sys_agent', schema=None) as batch_op:
        batch_op.create_index('idx_agent_tenant_id', ['tenant_id'], unique=False)

    op.create_table('t_sys_agent_knowledge_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_agent_knowledge_base'))
    )
    with op.batch_alter_table('t_sys_agent_knowledge_base', schema=None) as batch_op:
        batch_op.create_index('idx_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_knowledge_base_id', ['knowledge_base_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_agent_knowledge_base', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_base_id')
        batch_op.drop_index('idx_agent_id')

    op.drop_table('t_sys_agent_knowledge_base')
    with op.batch_alter_table('t_sys_agent', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_tenant_id')

    op.drop_table('t_sys_agent')
    # ### end Alembic commands ###
