"""empty message

Revision ID: 2fc60f57a788
Revises: ba5b69368858
Create Date: 2024-09-19 17:01:33.062560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fc60f57a788'
down_revision = 'ba5b69368858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_file_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parse_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentparsestatusenum'), nullable=False))
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('parse_status')
        batch_op.drop_column('upload_file_id')

    # ### end Alembic commands ###
