"""empty message

Revision ID: 8c2d50aca250
Revises: 
Create Date: 2024-09-07 21:48:05.966712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c2d50aca250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sys_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('password_salt', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_accounts')),
    sa.UniqueConstraint('email', name=op.f('uq_t_sys_accounts_email'))
    )
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.create_index('account_email_idx', ['email'], unique=False)

    op.create_table('t_sys_tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('custom_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_tenants'))
    )
    op.create_table('tenant_account_joins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_account_joins')),
    sa.UniqueConstraint('tenant_id', 'account_id', name='unique_tenant_account_join')
    )
    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
        batch_op.create_index('tenant_account_join_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('tenant_account_join_tenant_id_idx', ['tenant_id'], unique=False)

    op.drop_table('s2_dimension')
    op.drop_table('s2_user')
    op.drop_table('s2_app')
    op.drop_table('s2_auth_groups')
    op.drop_table('genre')
    op.drop_table('s2_pv_uv_statis')
    op.drop_table('files')
    op.drop_table('s2_chat_context')
    op.drop_table('singer')
    op.drop_table('s2_collect')
    op.drop_table('s2_stay_time_statis')
    op.drop_table('s2_domain')
    op.drop_table('s2_metric')
    op.drop_table('s2_term')
    op.drop_table('s2_data_set')
    op.drop_table('s2_plugin')
    op.drop_table('s2_system_config')
    with op.batch_alter_table('s2_chat_parse', schema=None) as batch_op:
        batch_op.drop_index('commonIndex')

    op.drop_table('s2_chat_parse')
    op.drop_table('s2_available_date_info')
    op.drop_table('artist')
    op.drop_table('s2_database')
    op.drop_table('s2_metric_query_default_config')
    op.drop_table('s2_user_department')
    op.drop_table('s2_chat_config')
    op.drop_table('s2_chat_query')
    op.drop_table('s2_chat')
    op.drop_table('s2_chat_memory')
    with op.batch_alter_table('s2_query_stat_info', schema=None) as batch_op:
        batch_op.drop_index('domain_index')

    op.drop_table('s2_query_stat_info')
    op.drop_table('song')
    op.drop_table('s2_semantic_pasre_info')
    op.drop_table('s2_tag')
    op.drop_table('s2_canvas')
    with op.batch_alter_table('s2_chat_statistics', schema=None) as batch_op:
        batch_op.drop_index('commonIndex')

    op.drop_table('s2_chat_statistics')
    op.drop_table('s2_query_rule')
    op.drop_table('s2_model_rela')
    op.drop_table('s2_dictionary_conf')
    op.drop_table('s2_tag_object')
    op.drop_table('s2_agent')
    op.drop_table('s2_dictionary_task')
    op.drop_table('s2_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s2_model',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('biz_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('alias', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('viewer', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('view_org', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('admin', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('admin_org', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('is_open', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('entity', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('drill_down_dimensions', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('database_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('model_detail', mysql.TEXT(collation='utf8_unicode_ci'), nullable=False),
    sa.Column('source_type', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True),
    sa.Column('depends', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('filter_sql', mysql.VARCHAR(collation='utf8_unicode_ci', length=1000), nullable=True),
    sa.Column('tag_object_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('ext', mysql.VARCHAR(collation='utf8_unicode_ci', length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_dictionary_task',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('config', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('elapsed_ms', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='字典运行任务表',
    mysql_comment='字典运行任务表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_agent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('examples', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('model', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('config', mysql.VARCHAR(collation='utf8_unicode_ci', length=6000), nullable=True),
    sa.Column('llm_config', mysql.VARCHAR(collation='utf8_unicode_ci', length=2000), nullable=True),
    sa.Column('model_config', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('prompt_config', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('multi_turn_config', mysql.VARCHAR(collation='utf8_unicode_ci', length=2000), nullable=True),
    sa.Column('visual_config', mysql.VARCHAR(collation='utf8_unicode_ci', length=2000), nullable=True),
    sa.Column('enable_search', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('enable_memory_review', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_tag_object',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='名称'),
    sa.Column('biz_name', mysql.VARCHAR(length=255), nullable=False, comment='英文名称'),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True, comment='描述'),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态'),
    sa.Column('sensitive_level', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='敏感级别'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False, comment='创建人'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True, comment='更新人'),
    sa.Column('ext', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='标签对象表',
    mysql_comment='标签对象表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_dictionary_conf',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('config', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='字典配置信息表',
    mysql_comment='字典配置信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_model_rela',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('from_model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('to_model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('join_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('join_condition', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_query_rule',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.INTEGER(display_width=10), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('rule_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('biz_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('rule', mysql.TEXT(), nullable=True),
    sa.Column('action', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ext', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='查询规则表',
    mysql_comment='查询规则表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_chat_statistics',
    sa.Column('question_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('chat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('query_text', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('interface_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cost', mysql.INTEGER(display_width=6), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('s2_chat_statistics', schema=None) as batch_op:
        batch_op.create_index('commonIndex', ['question_id'], unique=False)

    op.create_table('s2_canvas',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=True, comment='datasource、dimension、metric'),
    sa.Column('config', mysql.TEXT(), nullable=True, comment='config detail'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_tag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('ext', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_semantic_pasre_info',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('trace_id', mysql.VARCHAR(length=200), nullable=False, comment='查询标识'),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主体域ID'),
    sa.Column('dimensions', mysql.MEDIUMTEXT(), nullable=True, comment='查询相关的维度信息'),
    sa.Column('metrics', mysql.MEDIUMTEXT(), nullable=True, comment='查询相关的指标信息'),
    sa.Column('orders', mysql.MEDIUMTEXT(), nullable=True, comment='查询相关的排序信息'),
    sa.Column('filters', mysql.MEDIUMTEXT(), nullable=True, comment='查询相关的过滤信息'),
    sa.Column('date_info', mysql.MEDIUMTEXT(), nullable=True, comment='查询相关的日期信息'),
    sa.Column('limit', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='查询相关的limit信息'),
    sa.Column('native_query', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='1-明细查询,0-聚合查询'),
    sa.Column('sql', mysql.MEDIUMTEXT(), nullable=True, comment='解析后的sql'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False, comment='创建人'),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='运行状态'),
    sa.Column('elapsed_ms', mysql.BIGINT(display_width=10), autoincrement=False, nullable=True, comment='sql解析耗时'),
    sa.PrimaryKeyConstraint('id'),
    comment='语义层sql解析信息表',
    mysql_comment='语义层sql解析信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('song',
    sa.Column('imp_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('song_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('artist_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('f_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('g_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('languages', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('releasedate', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('resolution', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_query_stat_info',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('trace_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='查询标识'),
    sa.Column('model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('data_set_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='执行sql的用户'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('query_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='查询对应的场景'),
    sa.Column('query_type_back', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='查询类型, 0-正常查询, 1-预刷类型'),
    sa.Column('query_sql_cmd', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='对应查询的struct'),
    sa.Column('sql_cmd_md5', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='sql md5值'),
    sa.Column('query_struct_cmd', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='对应查询的struct'),
    sa.Column('struct_cmd_md5', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='sql md5值'),
    sa.Column('sql', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='对应查询的sql'),
    sa.Column('sql_md5', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='sql md5值'),
    sa.Column('query_engine', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='查询引擎'),
    sa.Column('elapsed_ms', mysql.BIGINT(display_width=10), autoincrement=False, nullable=True, comment='查询耗时'),
    sa.Column('query_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='查询最终状态'),
    sa.Column('native_query', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True, comment='1-明细查询,0-聚合查询'),
    sa.Column('start_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='sql开始日期'),
    sa.Column('end_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='sql结束日期'),
    sa.Column('dimensions', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql 涉及的维度'),
    sa.Column('metrics', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql 涉及的指标'),
    sa.Column('select_cols', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql select部分涉及的标签'),
    sa.Column('agg_cols', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql agg部分涉及的标签'),
    sa.Column('filter_cols', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql where部分涉及的标签'),
    sa.Column('group_by_cols', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql grouy by部分涉及的标签'),
    sa.Column('order_by_cols', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='sql order by部分涉及的标签'),
    sa.Column('use_result_cache', mysql.TINYINT(display_width=1), server_default=sa.text("'-1'"), autoincrement=False, nullable=True, comment='是否命中sql缓存'),
    sa.Column('use_sql_cache', mysql.TINYINT(display_width=1), server_default=sa.text("'-1'"), autoincrement=False, nullable=True, comment='是否命中sql缓存'),
    sa.Column('sql_cache_key', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='缓存的key'),
    sa.Column('result_cache_key', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='缓存的key'),
    sa.Column('query_opt_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='优化模式'),
    sa.PrimaryKeyConstraint('id'),
    comment='查询统计信息表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='查询统计信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('s2_query_stat_info', schema=None) as batch_op:
        batch_op.create_index('domain_index', ['model_id'], unique=False)

    op.create_table('s2_chat_memory',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=655), nullable=True, comment='用户问题'),
    sa.Column('agent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='助理ID'),
    sa.Column('db_schema', mysql.TEXT(), nullable=True, comment='Schema映射'),
    sa.Column('s2_sql', mysql.TEXT(), nullable=True, comment='大模型解析SQL'),
    sa.Column('status', mysql.CHAR(length=10), nullable=True, comment='状态'),
    sa.Column('llm_review', mysql.CHAR(length=10), nullable=True, comment='大模型评估结果'),
    sa.Column('llm_comment', mysql.TEXT(), nullable=True, comment='大模型评估意见'),
    sa.Column('human_review', mysql.CHAR(length=10), nullable=True, comment='管理员评估结果'),
    sa.Column('human_comment', mysql.TEXT(), nullable=True, comment='管理员评估意见'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_chat',
    sa.Column('chat_id', mysql.BIGINT(display_width=8), autoincrement=True, nullable=False),
    sa.Column('agent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chat_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('last_time', mysql.DATETIME(), nullable=True),
    sa.Column('creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('last_question', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_delete', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='is deleted'),
    sa.Column('is_top', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='is top'),
    sa.PrimaryKeyConstraint('chat_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_chat_query',
    sa.Column('question_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('agent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('query_text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('query_state', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('chat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('query_result', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('feedback', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=True),
    sa.Column('similar_queries', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=True),
    sa.Column('parse_time_cost', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('question_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_chat_config',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('chat_detail_config', mysql.MEDIUMTEXT(), nullable=True, comment='明细模式配置信息'),
    sa.Column('chat_agg_config', mysql.MEDIUMTEXT(), nullable=True, comment='指标模式配置信息'),
    sa.Column('recommended_questions', mysql.MEDIUMTEXT(), nullable=True, comment='推荐问题配置'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False, comment='创建人'),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=False, comment='更新人'),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='主题域扩展信息状态, 0-删除，1-生效'),
    sa.Column('llm_examples', mysql.TEXT(), nullable=True, comment='llm examples'),
    sa.PrimaryKeyConstraint('id'),
    comment='主题域扩展信息表',
    mysql_comment='主题域扩展信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_user_department',
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('department', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_metric_query_default_config',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('metric_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('default_config', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_database',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='名称'),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True, comment='描述'),
    sa.Column('version', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False, comment='类型 mysql,clickhouse,tdw'),
    sa.Column('config', mysql.TEXT(), nullable=False, comment='配置信息'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False, comment='创建人'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=False, comment='更新人'),
    sa.Column('admin', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('viewer', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='数据库实例表',
    mysql_comment='数据库实例表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('artist',
    sa.Column('artist_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('citizenship', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('gender', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('g_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_available_date_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_format', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('date_period', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('start_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('end_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('unavailable_date', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_chat_parse',
    sa.Column('question_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('chat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('parse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('query_text', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('parse_info', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('is_candidate', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='1是candidate,0是selected'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('s2_chat_parse', schema=None) as batch_op:
        batch_op.create_index('commonIndex', ['question_id'], unique=False)

    op.create_table('s2_system_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('admin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='系统管理员'),
    sa.Column('parameters', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='配置项'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_plugin',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=50), nullable=True, comment='DASHBOARD,WIDGET,URL'),
    sa.Column('data_set', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pattern', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('parse_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('parse_mode_config', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('config', mysql.TEXT(charset='utf8', collation='utf8_unicode_ci'), nullable=True),
    sa.Column('comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_data_set',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('biz_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('alias', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('data_set_detail', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('query_config', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3000), nullable=True),
    sa.Column('admin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3000), nullable=True),
    sa.Column('admin_org', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_term',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('alias', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('related_metrics', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('related_dimensions', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='术语表',
    mysql_comment='术语表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_metric',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='指标名称'),
    sa.Column('biz_name', mysql.VARCHAR(length=255), nullable=False, comment='字段名称'),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True, comment='描述'),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='指标状态'),
    sa.Column('sensitive_level', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='敏感级别'),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False, comment='指标类型'),
    sa.Column('type_params', mysql.TEXT(), nullable=False, comment='类型参数'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False, comment='创建人'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=False, comment='更新人'),
    sa.Column('data_format_type', mysql.VARCHAR(length=50), nullable=True, comment='数值类型'),
    sa.Column('data_format', mysql.VARCHAR(length=500), nullable=True, comment='数值类型参数'),
    sa.Column('alias', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('classifications', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('relate_dimensions', mysql.VARCHAR(length=500), nullable=True, comment='指标相关维度'),
    sa.Column('ext', mysql.TEXT(), nullable=True),
    sa.Column('define_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_publish', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True, comment='是否发布'),
    sa.PrimaryKeyConstraint('id'),
    comment='指标表',
    mysql_comment='指标表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_domain',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='主题域名称'),
    sa.Column('biz_name', mysql.VARCHAR(length=255), nullable=True, comment='内部名称'),
    sa.Column('parent_id', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='父主题域ID'),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='主题域状态'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True, comment='创建人'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True, comment='更新人'),
    sa.Column('admin', mysql.VARCHAR(length=3000), nullable=True, comment='主题域管理员'),
    sa.Column('admin_org', mysql.VARCHAR(length=3000), nullable=True, comment='主题域管理员组织'),
    sa.Column('is_open', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True, comment='主题域是否公开'),
    sa.Column('viewer', mysql.VARCHAR(length=3000), nullable=True, comment='主题域可用用户'),
    sa.Column('view_org', mysql.VARCHAR(length=3000), nullable=True, comment='主题域可用组织'),
    sa.Column('entity', mysql.VARCHAR(length=500), nullable=True, comment='主题域实体信息'),
    sa.PrimaryKeyConstraint('id'),
    comment='主题域基础信息表',
    mysql_comment='主题域基础信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_stay_time_statis',
    sa.Column('imp_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('stay_hours', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('page', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_collect',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('collect_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('singer',
    sa.Column('imp_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('singer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('act_area', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('song_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('genre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('js_play_cnt', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('down_cnt', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('favor_cnt', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_chat_context',
    sa.Column('chat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='context chat id'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='row modify time'),
    sa.Column('user', mysql.VARCHAR(length=64), nullable=True, comment='row modify user'),
    sa.Column('query_text', mysql.TEXT(), nullable=True, comment='query text'),
    sa.Column('semantic_parse', mysql.TEXT(), nullable=True, comment='parse data'),
    sa.Column('ext_data', mysql.TEXT(), nullable=True, comment='extend data'),
    sa.PrimaryKeyConstraint('chat_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('files',
    sa.Column('f_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('artist_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('file_size', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('duration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('formats', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.PrimaryKeyConstraint('f_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_pv_uv_statis',
    sa.Column('imp_date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('page', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('genre',
    sa.Column('g_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('most_popular_in', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('g_name'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_auth_groups',
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('config', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_app',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('config', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('qps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('app_secret', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('owner', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('salt', mysql.VARCHAR(length=256), nullable=True, comment='md5密码盐'),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('s2_dimension',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='维度ID'),
    sa.Column('model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='维度名称'),
    sa.Column('biz_name', mysql.VARCHAR(length=255), nullable=False, comment='字段名称'),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False, comment='描述'),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='维度状态,0正常,1下架'),
    sa.Column('sensitive_level', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True, comment='敏感级别'),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False, comment='维度类型 categorical,time'),
    sa.Column('type_params', mysql.TEXT(), nullable=True, comment='类型参数'),
    sa.Column('data_type', mysql.VARCHAR(length=50), nullable=True, comment='维度数据类型 varchar、array'),
    sa.Column('expr', mysql.TEXT(), nullable=False, comment='表达式'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False, comment='创建人'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=False, comment='更新人'),
    sa.Column('semantic_type', mysql.VARCHAR(length=20), nullable=False, comment='语义类型DATE, ID, CATEGORY'),
    sa.Column('alias', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('default_values', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('dim_value_maps', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('is_tag', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('ext', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='维度表',
    mysql_comment='维度表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
        batch_op.drop_index('tenant_account_join_tenant_id_idx')
        batch_op.drop_index('tenant_account_join_account_id_idx')

    op.drop_table('tenant_account_joins')
    op.drop_table('t_sys_tenants')
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.drop_index('account_email_idx')

    op.drop_table('t_sys_accounts')
    # ### end Alembic commands ###
