"""empty message

Revision ID: 9bb257773a67
Revises: c928c92e5616
Create Date: 2024-09-29 18:45:02.082559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bb257773a67'
down_revision = 'c928c92e5616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sys_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_conversation'))
    )
    with op.batch_alter_table('t_sys_conversation', schema=None) as batch_op:
        batch_op.create_index('idx_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)

    op.create_table('t_sys_conversation_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', mysql.LONGTEXT(), nullable=False),
    sa.Column('message_type', sa.Enum('USER', 'AGENT', name='conversationmessagetype'), server_default='user', nullable=False),
    sa.Column('pre_message_id', sa.Integer(), nullable=True),
    sa.Column('next_message_id', sa.Integer(), nullable=True),
    sa.Column('citation', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_conversation_message'))
    )
    with op.batch_alter_table('t_sys_conversation_message', schema=None) as batch_op:
        batch_op.create_index('idx_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_conversation_message', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_conversation_id')
        batch_op.drop_index('idx_agent_id')

    op.drop_table('t_sys_conversation_message')
    with op.batch_alter_table('t_sys_conversation', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_agent_id')

    op.drop_table('t_sys_conversation')
    # ### end Alembic commands ###
