"""empty message

Revision ID: b00f881359f4
Revises: 8c2d50aca250
Create Date: 2024-09-07 21:58:23.346103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b00f881359f4'
down_revision = '8c2d50aca250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sys_tenant_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_tenant_account')),
    sa.UniqueConstraint('tenant_id', 'account_id', name='uq_tenant_id_account_id')
    )
    with op.batch_alter_table('t_sys_tenant_account', schema=None) as batch_op:
        batch_op.create_index('idx_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
        batch_op.drop_index('tenant_account_join_account_id_idx')
        batch_op.drop_index('tenant_account_join_tenant_id_idx')
        batch_op.drop_index('unique_tenant_account_join')

    op.drop_table('tenant_account_joins')
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.drop_index('account_email_idx')

    with op.batch_alter_table('t_sys_tenants', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_t_sys_tenants_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_tenants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_t_sys_tenants_name'), type_='unique')

    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.create_index('account_email_idx', ['email'], unique=False)

    op.create_table('tenant_account_joins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('current', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=16), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('invited_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tenant_account_joins', schema=None) as batch_op:
        batch_op.create_index('unique_tenant_account_join', ['tenant_id', 'account_id'], unique=True)
        batch_op.create_index('tenant_account_join_tenant_id_idx', ['tenant_id'], unique=False)
        batch_op.create_index('tenant_account_join_account_id_idx', ['account_id'], unique=False)

    with op.batch_alter_table('t_sys_tenant_account', schema=None) as batch_op:
        batch_op.drop_index('idx_tenant_id')
        batch_op.drop_index('idx_account_id')

    op.drop_table('t_sys_tenant_account')
    # ### end Alembic commands ###
