"""empty message

Revision ID: ba5b69368858
Revises: d7948fddcb74
Create Date: 2024-09-16 20:50:42.509408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba5b69368858'
down_revision = 'd7948fddcb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sys_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('password_salt', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True),
    sa.Column('initialized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_account')),
    sa.UniqueConstraint('email', name=op.f('uq_t_sys_account_email'))
    )
    op.create_table('t_sys_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('parser_type', sa.Enum('PRESENTATION', 'LAWS', 'MANUAL', 'PAPER', 'RESUME', 'BOOK', 'QA', 'TABLE', 'NAIVE', 'PICTURE', 'ONE', 'AUDIO', 'EMAIL', 'KG', name='documentparsertypeenum'), nullable=False),
    sa.Column('parser_config', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=128), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('token_num', sa.Integer(), nullable=True),
    sa.Column('chunk_num', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('progress_msg', sa.Text(), nullable=True),
    sa.Column('process_begin_at', sa.DateTime(), nullable=True),
    sa.Column('process_duation', sa.Float(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_document'))
    )
    with op.batch_alter_table('t_sys_document', schema=None) as batch_op:
        batch_op.create_index('idx_document_knowledge_base_id', ['knowledge_base_id'], unique=False)

    op.create_table('t_sys_knowledge_base_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('has_permission', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_knowledge_base_permission'))
    )
    with op.batch_alter_table('t_sys_knowledge_base_permission', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_base_permissions_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_knowledge_base_permissions_knowledge_base_id', ['knowledge_base_id'], unique=False)
        batch_op.create_index('idx_knowledge_base_permissions_tenant_id', ['tenant_id'], unique=False)

    op.create_table('t_sys_tenant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('custom_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_tenant')),
    sa.UniqueConstraint('name', name=op.f('uq_t_sys_tenant_name'))
    )
    op.create_table('t_sys_upload_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('created_by_role', sa.String(length=255), server_default='account', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_sys_upload_file'))
    )
    with op.batch_alter_table('t_sys_upload_file', schema=None) as batch_op:
        batch_op.create_index('idx_upload_file_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('t_sys_tenants', schema=None) as batch_op:
        batch_op.drop_index('uq_t_sys_tenants_name')

    op.drop_table('t_sys_tenants')
    with op.batch_alter_table('t_sys_upload_files', schema=None) as batch_op:
        batch_op.drop_index('idx_upload_file_tenant_id')

    op.drop_table('t_sys_upload_files')
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.drop_index('uq_t_sys_accounts_email')

    op.drop_table('t_sys_accounts')
    with op.batch_alter_table('t_sys_knowledge_base_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_base_permissions_account_id')
        batch_op.drop_index('idx_knowledge_base_permissions_knowledge_base_id')
        batch_op.drop_index('idx_knowledge_base_permissions_tenant_id')

    op.drop_table('t_sys_knowledge_base_permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sys_knowledge_base_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('has_permission', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_sys_knowledge_base_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_base_permissions_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('idx_knowledge_base_permissions_knowledge_base_id', ['knowledge_base_id'], unique=False)
        batch_op.create_index('idx_knowledge_base_permissions_account_id', ['account_id'], unique=False)

    op.create_table('t_sys_accounts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_salt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_login_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('initialized_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.create_index('uq_t_sys_accounts_email', ['email'], unique=True)

    op.create_table('t_sys_upload_files',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('storage_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('extension', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by_role', mysql.VARCHAR(length=255), server_default=sa.text("'account'"), nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('used_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_sys_upload_files', schema=None) as batch_op:
        batch_op.create_index('idx_upload_file_tenant_id', ['tenant_id'], unique=False)

    op.create_table('t_sys_tenants',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=16), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('custom_config', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_sys_tenants', schema=None) as batch_op:
        batch_op.create_index('uq_t_sys_tenants_name', ['name'], unique=True)

    with op.batch_alter_table('t_sys_upload_file', schema=None) as batch_op:
        batch_op.drop_index('idx_upload_file_tenant_id')

    op.drop_table('t_sys_upload_file')
    op.drop_table('t_sys_tenant')
    with op.batch_alter_table('t_sys_knowledge_base_permission', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_base_permissions_tenant_id')
        batch_op.drop_index('idx_knowledge_base_permissions_knowledge_base_id')
        batch_op.drop_index('idx_knowledge_base_permissions_account_id')

    op.drop_table('t_sys_knowledge_base_permission')
    with op.batch_alter_table('t_sys_document', schema=None) as batch_op:
        batch_op.drop_index('idx_document_knowledge_base_id')

    op.drop_table('t_sys_document')
    op.drop_table('t_sys_account')
    # ### end Alembic commands ###
