"""empty message

Revision ID: c0c7190e3e20
Revises: b00f881359f4
Create Date: 2024-09-07 22:14:32.278208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c7190e3e20'
down_revision = 'b00f881359f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('initialized_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sys_accounts', schema=None) as batch_op:
        batch_op.drop_column('initialized_at')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
